# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuser',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='进入时间'),
        ),
    ]
