# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-31 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room_list',
            table='roomlist',
        ),
    ]
