# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-04 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20200331_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room_list',
            options={'verbose_name': '聊天室', 'verbose_name_plural': '聊天室列表'},
        ),
    ]
