# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20200404_1541'),
        ('room', '0003_auto_20200404_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('sent_time', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃')),
            ],
            options={
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
                'db_table': 'record',
            },
        ),
        migrations.AddField(
            model_name='room_list',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='活跃'),
        ),
        migrations.AddField(
            model_name='record',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room_list'),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User'),
        ),
    ]
