# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20200404_1541'),
        ('room', '0004_auto_20200404_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, unique=True, verbose_name='文件名')),
                ('fpath', models.CharField(max_length=70, verbose_name='文件位置')),
                ('updated_time', models.DateField(auto_now=True, verbose_name='上传时间')),
                ('froom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room_list')),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件列表',
                'db_table': 'files',
            },
        ),
    ]
