# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-04 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='froom',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='fuser',
            new_name='user',
        ),
    ]
