# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-05 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20200404_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='文件名'),
        ),
    ]
