# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20200405_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
    ]
