# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20200419_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_list',
            name='owner',
            field=models.IntegerField(default=0, verbose_name='管理员'),
        ),
        migrations.AlterModelTable(
            name='room_list',
            table='rooms',
        ),
    ]
