# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20200404_1541'),
        ('room', '0009_auto_20200419_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_list',
            name='user',
        ),
        migrations.AddField(
            model_name='room_list',
            name='user',
            field=models.ManyToManyField(to='userapp.User'),
        ),
    ]
