# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_auto_20200419_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_list',
            name='user',
        ),
    ]
