# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_remove_room_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_list',
            name='introduce',
            field=models.TextField(default='无', verbose_name='聊天室简介'),
        ),
    ]
