# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_auto_20200419_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='files',
            name='upload_time',
            field=models.DateTimeField(auto_now=True, verbose_name='上传时间'),
        ),
    ]
