# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-01 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_auto_20200426_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': '聊天记录', 'verbose_name_plural': '聊天记录'},
        ),
        migrations.AlterField(
            model_name='room_list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User'),
        ),
    ]
