# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql.Boy')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql.Girl')),
            ],
        ),
    ]
