# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(db_index=1, verbose_name='id'),
        ),
    ]
