# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20200328_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.IntegerField(db_index=0, default=0, verbose_name='id'),
            preserve_default=False,
        ),
    ]
