# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-30 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_auto_20200330_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=50, primary_key=True, verbose_name='书名'),
        ),
    ]
