# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(db_index=1, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=50, primary_key=True, verbose_name='书名'),
        ),
    ]
